<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        $menuItems = [
            [
                'name' => 'Wagyu Tataki',
                'description' => 'Seared Kagoshima A5 wagyu beef with truffle ponzu, microgreens, and crispy garlic',
                'price' => 38.00,
                'category' => 'Appetizers',
                'image_url' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
                'is_featured' => true,
                'is_available' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Fresh Uni Selection',
                'description' => 'Premium Hokkaido uni served traditional style with pickled ginger and wasabi',
                'price' => 42.00,
                'category' => 'Appetizers',
                'image_url' => 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80',
                'is_featured' => true,
                'is_available' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Chef\'s Omakase',
                'description' => '12-piece chef\'s selection of seasonal nigiri, prepared at the teppanyaki table',
                'price' => 85.00,
                'category' => 'Chef\'s Special',
                'image_url' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&q=80',
                'is_featured' => true,
                'is_available' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Black Cod Saikyo',
                'description' => 'Miso-marinated black cod with sweet onion puree and seasonal vegetables',
                'price' => 48.00,
                'category' => 'Main Course',
                'image_url' => 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80',
                'is_featured' => true,
                'is_available' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'A5 Wagyu Ribeye',
                'description' => 'Grade A5 Kagoshima wagyu with wasabi stem, ponzu, and Himalayan salt',
                'price' => 120.00,
                'category' => 'Main Course',
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
                'is_featured' => true,
                'is_available' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'Golden Lobster',
                'description' => 'Butter-poached Maine lobster with gold flake, yuzu kosho, and herb oil',
                'price' => 75.00,
                'category' => 'Main Course',
                'image_url' => 'https://images.unsplash.com/photo-1553247407-23251b9c19e0?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'Tuna Tartare',
                'description' => 'Fresh bluefin tuna with avocado, sesame, and wonton crisps',
                'price' => 32.00,
                'category' => 'Appetizers',
                'image_url' => 'https://images.unsplash.com/photo-1534604973900-c43aa9972157?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'Duck Breast',
                'description' => 'Five-spice duck breast with cherry gastrique and bok choy',
                'price' => 52.00,
                'category' => 'Main Course',
                'image_url' => 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'Miso Ramen',
                'description' => 'Rich tonkotsu broth with chashu, soft egg, and fresh noodles',
                'price' => 24.00,
                'category' => 'Noodles',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Udon with Tempura',
                'description' => 'Fresh udon in dashi broth with crispy shrimp tempura',
                'price' => 22.00,
                'category' => 'Noodles',
                'image_url' => 'https://images.unsplash.com/photo-1617093729463-2b85e536494b?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Salmon Teriyaki',
                'description' => 'Glazed Norwegian salmon with teriyaki sauce and steamed rice',
                'price' => 36.00,
                'category' => 'Main Course',
                'image_url' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 6,
            ],
            [
                'name' => 'Gyoza (6 pcs)',
                'description' => 'Pan-fried pork and vegetable dumplings with ponzu',
                'price' => 14.00,
                'category' => 'Appetizers',
                'image_url' => 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'Edamame',
                'description' => 'Steamed soybeans with sea salt',
                'price' => 8.00,
                'category' => 'Appetizers',
                'image_url' => 'https://images.unsplash.com/photo-1564894809611-1742fc40ed80?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'Mochi Ice Cream',
                'description' => 'Choice of green tea, mango, or red bean ice cream (3 pcs)',
                'price' => 12.00,
                'category' => 'Desserts',
                'image_url' => 'https://images.unsplash.com/photo-1582037928768-2da72c190d18?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Matcha Fondant',
                'description' => 'Warm matcha cake with vanilla bean ice cream',
                'price' => 16.00,
                'category' => 'Desserts',
                'image_url' => 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&q=80',
                'is_featured' => true,
                'is_available' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Sake Flight',
                'description' => 'Curated selection of three premium sakes',
                'price' => 28.00,
                'category' => 'Beverages',
                'image_url' => 'https://images.unsplash.com/photo-1510049521901-99f4f21bc5a8?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Sakura Martini',
                'description' => 'Cherry blossom vodka, elderflower, and lemon',
                'price' => 18.00,
                'category' => 'Beverages',
                'image_url' => 'https://images.unsplash.com/photo-1575023782549-62ca2d5b4b37?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Green Tea',
                'description' => 'Premium Japanese green tea',
                'price' => 6.00,
                'category' => 'Beverages',
                'image_url' => 'https://images.unsplash.com/photo-1564890368878-9f2204efc3ac?w=600&q=80',
                'is_featured' => false,
                'is_available' => true,
                'display_order' => 3,
            ],
        ];

        foreach ($menuItems as $item) {
            MenuItem::create($item);
        }
    }
}